version: '3.3'

services:
  challenge-web:
    image: fastapi-web:latest
    ports:
      - "3000:3000"
    environment:
      REACT_APP_URL_BASE: localhost:8000
    depends_on:
      - challenge

  challenge:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST     : postgres
      POSTGRES_USER     : postgres
      POSTGRES_PASSWORD : postgres
      POSTGRES_DB       : challenge_db
      POSTGRES_ECHO     : 'true'
    depends_on:
      - postgres
    volumes:
      - /opt/chanllenge/logs:/opt/chanllenge/logs

  postgres:
    build:
      context: postgresql
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - /opt/chanllenge/data:/var/lib/postgresql/data
